### post - Login usuario
POST http://localhost:4000/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email":"rcastrom@miumg.edu.gt",
  "password":"123456"
}


### post - Registrar usuario rcastrom
POST http://localhost:4000/api/user/register
Content-Type: application/json

{
  "name":"Roberto Castro",
  "email":"rcastrom@miumg.edu.gt",
  "password":"123456",
  "nick":"rcastro"
}

### post - Registrar usuario
POST http://localhost:4000/api/user/register
Content-Type: application/json

{
  "name":"Usuario 6",
  "email":"usuario6@dominio.com",
  "password":"123456",
  "nick":"Usuario 6"
}

### get - Obtener perfil
GET http://localhost:4000/api/user/profile/67045dab8be33474d96751ed HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3MDQ1ZGFiOGJlMzM0NzRkOTY3NTFlZCIsIm5hbWUiOiJSb2JlcnRvIENhc3RybyIsIm5pY2siOiJyY2FzdHJvIiwiZW1haWwiOiJyY2FzdHJvbUBtaXVtZy5lZHUuZ3QiLCJyb2xlIjoicm9sZV91c2VyIiwiaW1hZ2UiOiJkZWZhdWx0LnBuZyIsImlhdCI6MTcyOTAyNzYzMiwiZXhwIjoxNzMxNjE5NjMyfQ.d-Ep10ggC_AcYUYhDuryk85fGRx78oNblsVjhHVZXa8

### get - Obtener listado de usuarios por pagina
GET http://localhost:4000/api/user/list/1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3MDQ1ZGFiOGJlMzM0NzRkOTY3NTFlZCIsIm5hbWUiOiJSb2JlcnRvIENhc3RybyIsIm5pY2siOiJyY2FzdHJvIiwiZW1haWwiOiJyY2FzdHJvbUBtaXVtZy5lZHUuZ3QiLCJyb2xlIjoicm9sZV91c2VyIiwiaW1hZ2UiOiJkZWZhdWx0LnBuZyIsImlhdCI6MTcyOTAyNzYzMiwiZXhwIjoxNzMxNjE5NjMyfQ.d-Ep10ggC_AcYUYhDuryk85fGRx78oNblsVjhHVZXa8